<!-- Menu toggle -->
<a href="#menu" id="menuLink" class="menu-link">
    <!-- Hamburger icon -->
    <span></span>
</a>

<div id="menu">
    <div class="pure-menu pure-menu-open">
        <a class="pure-menu-heading" href="#">AJ Sistemas</a>

        <ul>
            <li class="menu-item-divided pure-menu-selected">
                <a href="index.php">Home</a>
            </li>

            <li>
                <a href="#">People</a>
            </li>

            <li><a href="#">News</a></li>

            <li><a href="#">About</a></li>
        </ul>
    </div>
</div>